"use client";

import { store } from "@/app/redux/store";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { whiteColor_v_2 } from "../../../color";
import Footer from "../components/Footer/Footer";
import HomePageHeader from "../components/HomePageHeader/HomePageHeader";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function productCart({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body
          className={inter.className}
          style={{ backgroundColor: whiteColor_v_2 }}
        >
          <HomePageHeader></HomePageHeader>
          {children}
          <Footer></Footer>
        </body>
      </Provider>
    </html>
  );
}
